### ISSUE TITLE
Bower Availability

### ISSUE THREAD

**Issue by texonidas** [geodatasource/country-region-dropdown-menu#1]
First off, can I just say this is an absolutely fantastic resource, and thank you so much for open sourcing it.

Can I suggest adding this as to Bower as well as npm? I'm sure I'm not alone in using Bower for anything that needs to be bundled in with my site, and npm for all my build processes.

**Comment by chrislim2888** [comment]
The package already in [npmjs](https://www.npmjs.com/package/country-region-dropdown-menu), but not yet in bower. Anyway, will look into bower for inclusion.

**Comment by geodatasource** [comment]
@texonidas We have registered our package at Bower. Now you may install the package with `bower install country-region-dropdown-menu`
