### ISSUE TITLE
Several countries on the dropdown are not in alphabetical order, making the plugin useless

### ISSUE THREAD

**Issue by Naxus28** [geodatasource/country-region-dropdown-menu#2]
<img width="670" alt="screen shot 2018-02-20 at 10 38 27 am" src="https://user-images.githubusercontent.com/5386170/36433388-5fc9760e-162a-11e8-8ce7-6e3b310bf8b3.png">

<img width="561" alt="screen shot 2018-02-20 at 10 40 04 am" src="https://user-images.githubusercontent.com/5386170/36433427-73b5f908-162a-11e8-84fb-e70eb7d73c29.png">

<img width="551" alt="screen shot 2018-02-20 at 10 41 20 am" src="https://user-images.githubusercontent.com/5386170/36433524-b68c9480-162a-11e8-94c2-0dd08d0d88d0.png">

<img width="558" alt="screen shot 2018-02-20 at 10 41 42 am" src="https://user-images.githubusercontent.com/5386170/36433525-b697f708-162a-11e8-9c6e-e56253ea527b.png">

<img width="548" alt="screen shot 2018-02-20 at 10 41 53 am" src="https://user-images.githubusercontent.com/5386170/36433527-b6a697ea-162a-11e8-987c-2bb0c1261395.png">

**Comment by geodatasource** [comment]
Hi @Naxus28 Thank you for the input.
We have reorganized the dropdown data in alphabetical order.
