### ISSUE TITLE
Flags class interfere with selection and page scrolling

### ISSUE THREAD

**Issue by Zenith-Nadir** [geodatasource/country-region-dropdown-menu#5]
Hello,
I have noticed when I chose the option with flags icons selection, I have a problem scrolling all countries selections to the very bottom of the selection field or the entire web page.
I am using Firefox v.67 on Ubuntu 18.04.2.
I have traced the cause of the issue is "class: gds-countryflag". When deleted, the selection and page scroll controls return (but flags are missing).
I was not able to correct this issue.
Also, is there any way to display a country flag at the selection bar, after choosing a country, next to the country name?
Sincerely,
Z-N

**Comment by geodatasource** [comment]
Hi @Zenith-Nadir 

Thank you for your feedback. As we are using JQuery select menu UI, the page scroll control will not be shown with the country flag. We will look into alternatives for the improvement.
