### ISSUE TITLE
Node.js / Angular Uses

### ISSUE THREAD

**Issue by Dev25-00** [geodatasource/country-region-dropdown-menu#6]
Need informations how to use in angular 8/9 (Node.js)

|Country:
    select.gds-cr(country-data-region-id="gds-cr-one",data-language="en").gds-countryflag
    |Region:
    select#gds-cr-one*

It's not ez to understand it's even not correspend to html code... Can some one make me see light about ways to use it ? thanks !

**Comment by geodatasource** [comment]
Hi,

Can you show us your code for the implementation?
