### ISSUE TITLE
Sort order when using a language other than English

### ISSUE THREAD

**Issue by Slos** [geodatasource/country-region-dropdown-menu#7]
Hello,

Really nice NPM package! Just one thing, the sort order of the countries is wrong when choosing a display language other than English. Please see the screenshots for reference.

![Screenshot 2021-05-15 at 19 04 11](https://user-images.githubusercontent.com/9729859/118372184-998da300-b5b0-11eb-8a0c-cecca3bc2e26.png)

**Comment by geodatasource** [comment]
Hi @Slos,

Thank you for the input. We have updated the package. Kindly get the latest version.
